### ISSUE TITLE
How to share "raw" folder video?

### ISSUE THREAD

**Issue by vinod1988** [commonsguy/cwac-provider#14]
Here is y source code. Show a message "No apps can perform this action"
 

                 Intent localIntent = new Intent(Intent.ACTION_SEND);
                String rawId = "raw/"+CorporateAdaptor.this.rawVideoId ;

                DebugLog.d("rawId=="+rawId);

                String  extension =".mp4";

                localIntent.setType(MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension));
                localIntent.putExtra(Intent.EXTRA_STREAM, getUri(rawId));
                localIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

                CorporateAdaptor.this.mContext.startActivity(Intent.createChooser(localIntent, "Where you want to share?"));

Here is my manifest code:
<provider
			android:name="com.commonsware.cwac.provider.StreamProvider"
			android:authorities="com.runtime_solutions.videoshare"
			android:exported="false"
			android:grantUriPermissions="true">
			<meta-data
			android:name="com.commonsware.cwac.provider.STREAM_PROVIDER_PATHS"
			android:resource="@xml/paths"/>
			<meta-data
				android:name="com.commonsware.cwac.provider.USE_LEGACY_CURSOR_WRAPPER"
				android:value="true"/>
		</provider>

	<asset name="raw" path="" />

**Comment by commonsguy** [comment]
This Java code has nothing to do with my library.

Also, this is an issue tracker, not a support board. Please read [the project documentation](https://github.com/commonsguy/cwac-provider#questions) to learn where and how to ask questions.

**Comment by commonsguy** [comment]
`<asset name="raw" path="" />` shares `assets/` with a `Uri` using a path segment named `raw`. This does not appear to be what you want.

This library does not support serving a arbitrary number of raw resources, which appears to be what you are trying to do. Each raw resource would need its own `<raw-resource>` element in the provider configuration (instead of `<asset>`), with a `path` attribute providing the base name of the resource (e.g,. `<raw-resource name="test1" path="something">` would be able to serve a `res/raw/something.mp4` file).
