### ISSUE TITLE
getUriPrefix() doesn't return anything

### ISSUE THREAD

**Issue by ChopSuey133** [commonsguy/cwac-provider#23]
Hello!

I already asked in stackoverflow but I couldn't resolve my issue.
If I am sending the my Authority to Streamprovider.getUriPrefix(Authority) it doesn't return anything.

Attached is a sample project where this happens. Click the button for an Intent.ACTION_SEND.
[app.zip](https://github.com/commonsguy/cwac-provider/files/643913/app.zip)

**Comment by commonsguy** [comment]
That is not a project. It is a module from a project.

I added that module to a newly-created project, replacing the generated `app` module. I then put a breakpoint in your code, ran the app on a Nexus 5 (Android 6.0.1), and the `Uri` has the prefix, as it is supposed to:

![androidstudio](https://cloud.githubusercontent.com/assets/103772/21074867/c000a300-bed1-11e6-9eaa-6e8053f90e75.png)

Hence, I cannot reproduce your problem.

I suggest that you completely uninstall your app (i.e., through Settings > Apps), then try it again.

Also note that you probably want `appendEncodedPath()`, not `appendPath()`, for `ASSET_PATHS`, since you have a `/` in `ASSET_PATHS` that you (presumably) want to keep as a `/` in the resulting `Uri`.

If you continue to encounter problems, and you can provide a sample project and steps that *anyone* can run to reproduce the problem, comment back here, and I can re-open this issue.
