### ISSUE TITLE
Question: How to use for sharing file from resources (raw, for example) or from URL ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [commonsguy/cwac-provider#24]
The sample shows about assets, yet the repo says it's possible to share a file that exists in the raw folder:

> StreamProvider adds support for:
> 
> <raw-resource> for serving a particular raw resource, where the path is the name of the raw resource (without file extension)

However, I can't find an explanation or a demo of how to do it. Only thing I've found is another issue talking about it: https://github.com/commonsguy/cwac-provider/issues/14 , but I don't see the code to do it.

Can you please show how to do it? Maybe even update the repo main page?

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. Please read the project documentation for [how to get support](https://github.com/commonsguy/cwac-provider#questions).

> I can't find an explanation

[Use the `<raw-resource>` element](https://github.com/commonsguy/cwac-provider#metadata-elements).

> or a demo of how to do it

An example `<raw-resource>` element is in [the instrumentation test suite](https://github.com/commonsguy/cwac-provider/blob/v0.5.0/provider/src/androidTest/res/xml/paths.xml). It points to [the `res/raw/something.bin` raw resource](https://github.com/commonsguy/cwac-provider/blob/v0.5.0/provider/src/androidTest/res/raw/something.bin). That particular `Uri` is then used in the instrumentation testing code, in [the `RawResourceProviderTest` class](https://github.com/commonsguy/cwac-provider/blob/v0.5.0/provider/src/androidTest/java/com/commonsware/cwac/provider/test/RawResourceProviderTest.java) and superclasses.

> Can you please show how to do it? Maybe even update the repo main page?

I would prefer that people use assets.

**Comment by AndroidDeveloperLB** [comment]
Well I had an issue of using this library, because it lacks the explanation of how to use this particular feature that it says it supports.
About assets vs raw, I don't think there is much difference, no?
About the test, are you talking about this:
https://github.com/commonsguy/cwac-provider/blob/v0.5.0/provider/src/androidTest/java/com/commonsware/cwac/provider/test/RawResourceProviderTest.java
?
But how could it be this way? Where's the resource id (or name) being a parameter?  The docs say it's supposed to be "path is the name of the raw resource (without file extension)" , yet the only function there that has a parameter, has "Uri root" as parameter, and the other one has a resource id inside itself...

**Comment by commonsguy** [comment]
>Well I had an issue of using this library, because it lacks the explanation of how to use this particular feature that it says it supports.

If you do not wish to follow documented instructions for getting support, then do not use the library.

> are you talking about this

Considering that I linked to it, yes

> Where's the resource id (or name) being a parameter?

It is not a parameter. An individual `<raw-resource>` element points to a single raw resource. I am not exposing all raw resources via a single element.

**Comment by AndroidDeveloperLB** [comment]
That's how it works for all repos. Not just here. People ask questions inside the website of the repo. This includes issues of all types. Not just bug reports. And what I wrote is about docuementation because it is missing . That's not something that's supposed to be asked on StackOverflow. 

About the raw resource sharing, I don't understand. Suppose I have 20 raw resources, and I want to be able to share each of them. I would need a function that has the raw resource id as a parameter. It doesn't make sense to write code/xml for each of them.

**Comment by commonsguy** [comment]
> That's how it works for all repos.

No, it does not.

>  It doesn't make sense to write code/xml for each of them.

Then write your own `ContentProvider` that works the way that you want.

**Comment by AndroidDeveloperLB** [comment]
You say that this is how it works on this library? That for each resource, an xml tag will be needed to be written?

**Comment by commonsguy** [comment]
> That for each resource, an xml tag will be needed to be written?

For raw resources, yes. This is the only tag with this limitation, as I did not want to expose all of raw resources via a single tag. Everything else has paths (assets, filesystem locations), and so you can control the scope of what gets exposed by putting your content in separate directories. That is not possible with resources, as they do not have paths.

Mostly, `<raw-resource>` is there for apps that, for legacy reasons, are stuck with raw resources. The flexibility that raw resources give developers &mdash; being able to have different resource editions based on configurations &mdash; is somewhat counter to publishing that content via a provider. For example, suppose the client app messes with `Locale` to force a particular language. When it makes a request of your `StreamProvider` for a raw resource, and you have different raw resources for different languages, what gets returned? AFAIK, it will be the system language's resource, not the client app's language's resource, since your app will not have the modified `Locale`. It is that sort of edge and corner case that I would like developers to avoid, by not publishing raw resources via this provider.

If you wish to use raw resources, you are welcome to do so, subject to the limitations of the library, or subject to the limitations of your own `ContentProvider`. I made `StreamProvider` available as it scratched an itch of mine, and I elected to scratch the itches corresponding with some low-hanging fruit (to mix metaphors). I do not promise that any of my open source code will scratch all possible itches.

**Comment by AndroidDeveloperLB** [comment]
ok thanks. 
Please change the docs and/or demo to include enough information for sharing resources.

BTW, the sample doesn't work well for the view option of pdf files: No idea why, but Google's app (I think it's of Google) for opening it failed to open this file.

**Comment by commonsguy** [comment]
> Please change the docs and/or demo to include enough information for sharing resources.

No.

> the sample doesn't work well for the view option of pdf files

See issue #21.

**Comment by AndroidDeveloperLB** [comment]
So you say it's probably issue with Google's app.
What do you mean "I expect to leave it as it is."  ? It's important to show how to use features of the library.

**Comment by commonsguy** [comment]
See issue #26.

**Comment by AndroidDeveloperLB** [comment]
Seems like a new issue, but there is no explanation for this. A raw resource should be safe to use just as a file in assets folder. Why deprecate it?
